-- =============================================================================
-- Avis (reviews) — 2026-06-20
-- Table des avis + recalcul SERVEUR des agrégats (restaurants.rating / reviews)
-- via trigger : à chaque insert/update/delete d'un avis, on recalcule la moyenne
-- et le nombre d'avis du restaurant concerné. Ainsi l'accueil lit directement
-- restaurants.rating/reviews sans charger les avis, et la valeur ne peut pas
-- être falsifiée depuis le client (calcul en base, RLS contournée par le trigger).
--
-- À exécuter sur le projet Supabase (ref ilonqaqyqmvsfskwgqka).
--
-- Choix de conception (modifiable) :
--  - 1 avis par utilisateur et par restaurant (unique) → éditable, pas de bourrage.
--  - note obligatoire 1..5 ; commentaire optionnel.
--  - lecture par tous les authentifiés ; écriture = son propre avis.
--  - modération : un admin peut supprimer n'importe quel avis.
-- =============================================================================

-- 1) Table ---------------------------------------------------------------------
create table if not exists public.reviews (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  user_id       uuid   not null default auth.uid() references auth.users(id) on delete cascade,
  rating        int    not null check (rating between 1 and 5),
  comment       text,
  unique (restaurant_id, user_id)
);

-- 2) updated_at automatique ----------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_reviews_updated_at on public.reviews;
create trigger trg_reviews_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

-- 3) Recalcul des agrégats du restaurant --------------------------------------
-- security definer : l'auteur d'un avis (non-admin) ne peut pas écrire dans
-- restaurants (RLS admin-only). Le trigger s'exécute donc avec les droits du
-- propriétaire (postgres) pour mettre à jour les agrégats.
create or replace function public.recalc_restaurant_rating()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  rid bigint := coalesce(new.restaurant_id, old.restaurant_id);
begin
  update public.restaurants r
  set reviews = agg.cnt,
      rating  = agg.avg
  from (
    select count(*)::int as cnt,
           coalesce(round(avg(rating)::numeric, 1), 0)::real as avg
    from public.reviews
    where restaurant_id = rid
  ) agg
  where r.id = rid;

  -- Si un update a déplacé l'avis vers un autre resto, recalculer l'ancien.
  if tg_op = 'UPDATE' and new.restaurant_id is distinct from old.restaurant_id then
    update public.restaurants r
    set reviews = agg.cnt,
        rating  = agg.avg
    from (
      select count(*)::int as cnt,
             coalesce(round(avg(rating)::numeric, 1), 0)::real as avg
      from public.reviews
      where restaurant_id = old.restaurant_id
    ) agg
    where r.id = old.restaurant_id;
  end if;

  return null; -- trigger AFTER
end;
$$;

drop trigger if exists trg_reviews_recalc on public.reviews;
create trigger trg_reviews_recalc
after insert or update or delete on public.reviews
for each row execute function public.recalc_restaurant_rating();

-- 4) RLS -----------------------------------------------------------------------
alter table public.reviews enable row level security;

drop policy if exists "reviews select authenticated" on public.reviews;
create policy "reviews select authenticated"
on public.reviews for select to authenticated
using (true);

drop policy if exists "reviews insert own" on public.reviews;
create policy "reviews insert own"
on public.reviews for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "reviews update own" on public.reviews;
create policy "reviews update own"
on public.reviews for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "reviews delete own" on public.reviews;
create policy "reviews delete own"
on public.reviews for delete to authenticated
using (user_id = auth.uid());

-- Modération : un admin peut supprimer n'importe quel avis.
drop policy if exists "reviews delete admin" on public.reviews;
create policy "reviews delete admin"
on public.reviews for delete to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  )
);

-- 5) (optionnel) backfill des agrégats si des avis existent déjà --------------
-- update public.restaurants r
-- set reviews = agg.cnt, rating = agg.avg
-- from (
--   select restaurant_id,
--          count(*)::int as cnt,
--          round(avg(rating)::numeric, 1)::real as avg
--   from public.reviews group by restaurant_id
-- ) agg
-- where r.id = agg.restaurant_id;
