-- =============================================================================
-- Photos restaurants (galerie collaborateurs) — 2026-06-20
-- Stockage des photos dans Supabase Storage (bucket objet, séparé du quota de la
-- base Postgres). La base ne garde que des MÉTADONNÉES : qui a uploadé, quand,
-- le chemin du fichier dans le bucket. Les binaires ne touchent jamais Postgres.
--
-- Modèle calqué sur public.reviews : contenu créé par les collaborateurs,
-- modéré par les admins (suppression de n'importe quelle photo).
--
-- À exécuter sur le projet Supabase (ref ilonqaqyqmvsfskwgqka).
-- =============================================================================

-- 1) Bucket de stockage --------------------------------------------------------
-- public = true → lecture via URL publique sans signature (simple, suffisant ici :
-- des photos de restos n'ont rien de confidentiel). L'écriture reste protégée
-- par les policies storage ci-dessous.
insert into storage.buckets (id, name, public)
values ('restaurant-photos', 'restaurant-photos', true)
on conflict (id) do nothing;

-- 2) Table de métadonnées ------------------------------------------------------
create table if not exists public.restaurant_photos (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  user_id       uuid   not null default auth.uid() references auth.users(id) on delete cascade,
  storage_path  text   not null unique,  -- chemin dans le bucket: {restaurant_id}/{uuid}.{ext}
  width         int,
  height        int
);

create index if not exists idx_restaurant_photos_restaurant
  on public.restaurant_photos (restaurant_id, created_at desc);

-- 2bis) Limite : 1 photo par personne et par restaurant, SAUF les admins -------
-- Un index unique (restaurant_id, user_id) ne convient pas : il bloquerait aussi
-- les admins. On passe donc par un trigger qui exempte les admins.
create or replace function public.enforce_one_photo_per_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- La limite porte sur ce qu'un UTILISATEUR peut saisir lui-même. Un admin
  -- n'est pas limité (et peut poster au nom d'un autre via user_id), donc on
  -- exempte selon l'UPLOADEUR réel (auth.uid()), pas l'auteur attribué.
  if exists (
    select 1 from public.users where id = auth.uid() and role = 'admin'
  ) then
    return new;
  end if;

  if exists (
    select 1 from public.restaurant_photos
    where restaurant_id = new.restaurant_id and user_id = new.user_id
  ) then
    raise exception 'Une seule photo par personne et par restaurant'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_one_photo_per_user on public.restaurant_photos;
create trigger trg_one_photo_per_user
before insert on public.restaurant_photos
for each row execute function public.enforce_one_photo_per_user();

-- 3) RLS table -----------------------------------------------------------------
alter table public.restaurant_photos enable row level security;

drop policy if exists "restaurant_photos select authenticated" on public.restaurant_photos;
create policy "restaurant_photos select authenticated"
on public.restaurant_photos for select to authenticated
using (true);

-- Un utilisateur n'écrit que sa propre photo ; un admin peut attribuer la photo
-- à n'importe quel user_id (poster au nom d'un autre).
drop policy if exists "restaurant_photos insert own" on public.restaurant_photos;
create policy "restaurant_photos insert own"
on public.restaurant_photos for insert to authenticated
with check (
  user_id = auth.uid()
  or exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  )
);

drop policy if exists "restaurant_photos delete own" on public.restaurant_photos;
create policy "restaurant_photos delete own"
on public.restaurant_photos for delete to authenticated
using (user_id = auth.uid());

-- Modération : un admin peut supprimer n'importe quelle photo.
drop policy if exists "restaurant_photos delete admin" on public.restaurant_photos;
create policy "restaurant_photos delete admin"
on public.restaurant_photos for delete to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  )
);

-- 4) RLS storage.objects (backstop côté fichiers) ------------------------------
-- Le bucket étant public, la LECTURE des fichiers se fait via l'URL publique sans
-- policy. Ces policies encadrent l'écriture/suppression depuis le client.

drop policy if exists "restaurant-photos read" on storage.objects;
create policy "restaurant-photos read"
on storage.objects for select to authenticated
using (bucket_id = 'restaurant-photos');

drop policy if exists "restaurant-photos insert own" on storage.objects;
create policy "restaurant-photos insert own"
on storage.objects for insert to authenticated
with check (bucket_id = 'restaurant-photos' and owner = auth.uid());

drop policy if exists "restaurant-photos delete own" on storage.objects;
create policy "restaurant-photos delete own"
on storage.objects for delete to authenticated
using (bucket_id = 'restaurant-photos' and owner = auth.uid());

-- Modération fichiers : un admin peut supprimer n'importe quel fichier du bucket.
drop policy if exists "restaurant-photos delete admin" on storage.objects;
create policy "restaurant-photos delete admin"
on storage.objects for delete to authenticated
using (
  bucket_id = 'restaurant-photos'
  and exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  )
);
