-- =============================================================================
-- Limite de demandes d'accès par IP — 2026-06-19
-- Complément à l'option B : plafonne le nombre de demandes ABOUTIES par source
-- (IP hashée) sur une fenêtre glissante, pour empêcher une même personne de
-- créer plein d'adresses. Seuil/fenêtre gérés dans l'Edge Function request-access.
--
-- ⚠️ Garde-fou IMPARFAIT (contournable via VPN/4G/incognito ; et plusieurs vrais
--    utilisateurs derrière un même NAT @infflux.com partagent la même IP). Le
--    seuil est donc volontairement généreux. Le vrai anti-bot reste Turnstile.
-- =============================================================================

-- Table de comptage : écrite/lue UNIQUEMENT par l'Edge Function (service_role).
-- RLS activée SANS aucune policy ⇒ aucun accès anon/authenticated (le
-- service_role contourne la RLS). L'IP n'est jamais stockée en clair (hash SHA-256).
create table if not exists public.access_request_ip_log (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.access_request_ip_log enable row level security;

-- Index pour le comptage "cette IP sur les dernières 24 h".
create index if not exists access_request_ip_log_lookup
  on public.access_request_ip_log (ip_hash, created_at);
