-- =============================================================================
-- Création de la table `badges` — 2026-06-14
-- La section admin "Badges" (adminSections.ts) lit/écrit public.badges, mais la
-- table n'avait jamais été créée (la DB était en pause au moment du dev) =>
-- l'onglet Badges de l'admin plantait ("relation badges does not exist").
--
-- Structure calquée sur public.tags (id bigint identity + label text unique).
-- RLS identique à tags : lecture pour tout user connecté, écriture admin-only.
--
-- NB : le sélecteur de badges des restaurants (BadgesToggles) reste basé sur
--      badgeMap (hardcodé). Cette table ne pilote donc PAS le picker — elle sert
--      uniquement à l'écran d'admin. On la seed avec les 5 badges de badgeMap
--      pour cohérence. (Unifier badgeMap <-> table = chantier futur optionnel.)
-- =============================================================================

create table if not exists public.badges (
  id bigint generated by default as identity primary key,
  label text not null unique
);

alter table public.badges enable row level security;

-- Lecture : tout utilisateur connecté
create policy "Enable read access for all users"
on public.badges for select to authenticated
using (true);

-- Insert / Update / Delete : admins uniquement (mêmes règles que tags)
create policy "Enable insert for admins only"
on public.badges for insert to authenticated
with check (exists (
  select 1 from public.users where users.id = auth.uid() and users.role = 'admin'
));

create policy "Enable update for admins only"
on public.badges for update to authenticated
using (exists (
  select 1 from public.users where users.id = auth.uid() and users.role = 'admin'
))
with check (exists (
  select 1 from public.users where users.id = auth.uid() and users.role = 'admin'
));

create policy "Enable delete for admins only"
on public.badges for delete to authenticated
using (exists (
  select 1 from public.users where users.id = auth.uid() and users.role = 'admin'
));

-- Privilèges Data API (comme les autres tables ; la sécurité réelle = RLS ci-dessus)
grant all on table public.badges to anon, authenticated, service_role;

-- Seed : les 5 badges réellement utilisés (clés de badgeMap)
insert into public.badges (label) values
  ('Option Végétarienne'),
  ('Sur Place'),
  ('À Emporter'),
  ('Bar'),
  ('TooGoodToGo')
on conflict (label) do nothing;
