-- =============================================================================
-- Réactions emoji (👍 ❤️ 😋) sur avis & photos — 2026-06-27
-- Table générique polymorphe : une réaction cible soit un avis (review), soit
-- une photo (photo). Un utilisateur peut poser chaque emoji au plus une fois par
-- cible (toggle). Lecture par tous les authentifiés ; on ne gère/supprime que
-- ses propres réactions. Nettoyage auto des réactions quand la cible disparaît.
--
-- À exécuter sur le projet Supabase (ref ilonqaqyqmvsfskwgqka).
-- =============================================================================

-- 1) Table ---------------------------------------------------------------------
create table if not exists public.reactions (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('review', 'photo')),
  target_id   bigint not null,
  emoji       text not null,
  unique (user_id, target_type, target_id, emoji)
);

-- Lecture groupée par cible (liste des réactions d'un avis/d'une photo).
create index if not exists reactions_target_idx
  on public.reactions (target_type, target_id);

-- 2) RLS -----------------------------------------------------------------------
alter table public.reactions enable row level security;

drop policy if exists "reactions select authenticated" on public.reactions;
create policy "reactions select authenticated"
on public.reactions for select to authenticated
using (true);

drop policy if exists "reactions insert own" on public.reactions;
create policy "reactions insert own"
on public.reactions for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "reactions delete own" on public.reactions;
create policy "reactions delete own"
on public.reactions for delete to authenticated
using (user_id = auth.uid());

-- 3) Nettoyage des réactions orphelines ---------------------------------------
-- target_id est polymorphe → pas de FK. On supprime donc les réactions liées
-- quand l'avis ou la photo cible est supprimé(e). security definer : l'auteur
-- (non-admin) qui supprime SON avis/SA photo doit pouvoir effacer les réactions
-- des AUTRES sur cette cible (que la RLS lui interdirait sinon).
create or replace function public.cleanup_reactions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.reactions
  where target_type = tg_argv[0] and target_id = old.id;
  return old;
end;
$$;

drop trigger if exists trg_reviews_cleanup_reactions on public.reviews;
create trigger trg_reviews_cleanup_reactions
after delete on public.reviews
for each row execute function public.cleanup_reactions('review');

drop trigger if exists trg_photos_cleanup_reactions on public.restaurant_photos;
create trigger trg_photos_cleanup_reactions
after delete on public.restaurant_photos
for each row execute function public.cleanup_reactions('photo');
