-- =============================================================================
-- Prix du midi (fourchette par personne) — 2026-09-28
-- La fourchette d'un restaurant vient UNIQUEMENT de l'expérience des
-- collaborateurs : chacun déclare ce qu'il dépense sur place — une borne basse
-- (« d'habitude je paie ») et une borne haute facultative (« jusqu'à ») qui
-- vaut la basse si on la laisse vide. Une déclaration par personne et par
-- restaurant, modifiable. Pas de saisie administrateur : personne n'a les
-- menus de tous les restos sous la main, et une fourchette inventée au jugé
-- vaut moins que celle de quelqu'un qui y a mangé.
--
-- Agrégat = MÉDIANE des bornes basses (arrondie à l'euro inférieur) et MÉDIANE
-- des bornes hautes (arrondie à l'euro supérieur), et non la moyenne : un collègue qui
-- déclare 45 € ne tire pas toute la fourchette. La médiane étant monotone, la
-- borne basse reste toujours ≤ la borne haute.
-- Passer à des quartiles (p25/p75) élargirait la fourchette et demanderait du
-- volume pour vouloir dire quelque chose : c'est un simple changement des deux
-- fractions ci-dessous dans apply_restaurant_prices, si l'usage le réclame.
-- Une seule déclaration suffit à publier une fourchette : à une centaine de
-- collaborateurs, exiger un quorum laisserait la plupart des restos muets.
--
-- Comme pour reviews → restaurants.rating/reviews, les agrégats sont recalculés
-- côté SERVEUR par trigger : la grille lit directement les colonnes du resto,
-- sans charger les déclarations, et les valeurs ne peuvent pas être falsifiées
-- depuis le client (RLS contournée par le trigger security definer).
--
-- Les montants individuels ne sont lisibles que par leur auteur (et les
-- admins) : la fiche n'affiche que la fourchette et le nombre de contributeurs.
--
-- À exécuter sur le projet Supabase (ref ilonqaqyqmvsfskwgqka). Le script est
-- idempotent : il peut être rejoué, y compris sur une base où une version
-- antérieure (saisie admin, déclaration à un seul montant) a déjà tourné.
--
-- Choix de conception (modifiable) :
--  - montants saisis au centime près (numeric(5,2)), 1..200 € (un déjeuner,
--    pas une note de frais). La fourchette PUBLIÉE, elle, reste en euros
--    entiers : « 12-19 € » se lit mieux que « 12,33-18,75 € ».
-- =============================================================================

-- 0) Reprise d'une version antérieure de ce script -----------------------------
-- Une première mouture prévoyait une fourchette saisie par un ADMIN
-- (restaurants.price_min / price_max) et une déclaration à un seul montant
-- (restaurant_prices.amount). Les deux ont été abandonnées. Ce bloc remet une
-- base déjà migrée dans le bon état ; il ne fait rien sur une base vierge.

-- Triggers et fonctions D'ABORD : la mise à niveau des colonnes (point 2) écrit
-- dans restaurant_prices, ce qui réveillerait le trigger de recalcul — encore
-- compilé sur `amount`, la colonne qu'on vient justement de renommer. Ils sont
-- remontés au point 3, et le point 4 rattrape les agrégats.
do $$
begin
  if to_regclass('public.restaurant_prices') is not null then
    drop trigger if exists trg_restaurant_prices_recalc on public.restaurant_prices;
    drop trigger if exists trg_restaurant_prices_updated_at on public.restaurant_prices;
  end if;
end $$;

drop function if exists public.recalc_restaurant_prices();
drop function if exists public.apply_restaurant_prices(bigint);

-- price_ref doit être supprimée AVANT price_min/price_max : c'est une colonne
-- générée qui les référence. Elle est recréée au point 1, sans perte (elle ne
-- contient rien d'autre que le calcul).
alter table public.restaurants
  drop constraint if exists restaurants_price_admin_range;
alter table public.restaurants drop column if exists price_ref;
alter table public.restaurants drop column if exists price_min;
alter table public.restaurants drop column if exists price_max;

-- 1) Colonnes d'agrégat sur le restaurant --------------------------------------
alter table public.restaurants
  add column if not exists price_low   int,  -- médiane des bornes basses (trigger)
  add column if not exists price_high  int,  -- médiane des bornes hautes (trigger)
  add column if not exists price_count int not null default 0;

-- Prix de référence : ce sur quoi le FILTRE compare (un simple gte/lte
-- PostgREST). NULL = prix inconnu → le resto sort de la liste dès qu'une plage
-- de prix est demandée, sans condition supplémentaire.
alter table public.restaurants
  add column if not exists price_ref real generated always as (
    ((price_low + price_high) / 2.0)::real
  ) stored;

-- 2) Déclarations --------------------------------------------------------------
create table if not exists public.restaurant_prices (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  user_id       uuid   not null default auth.uid() references auth.users(id) on delete cascade,
  amount_min    numeric(5,2) not null check (amount_min between 1 and 200),
  amount_max    numeric(5,2) not null check (amount_max between 1 and 200),
  constraint restaurant_prices_range check (amount_max >= amount_min),
  unique (restaurant_id, user_id)
);

-- Mise à niveau d'une table créée par la version « un seul montant » : `amount`
-- devient la borne basse, la borne haute est ajoutée et vaut la basse pour les
-- déclarations déjà saisies (c'est exactement ce que veut dire un seul chiffre).
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'restaurant_prices'
      and column_name = 'amount'
  ) and not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'restaurant_prices'
      and column_name = 'amount_min'
  ) then
    alter table public.restaurant_prices rename column amount to amount_min;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'restaurant_prices'
      and column_name = 'amount_max'
  ) then
    alter table public.restaurant_prices add column amount_max numeric(5,2);
    update public.restaurant_prices set amount_max = amount_min;
    alter table public.restaurant_prices
      alter column amount_max set not null,
      add constraint restaurant_prices_amount_max_check
        check (amount_max between 1 and 200);
  end if;

  -- Montants passés de l'entier au centime (no-op si déjà fait).
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'restaurant_prices'
      and column_name = 'amount_min' and data_type <> 'numeric'
  ) then
    alter table public.restaurant_prices
      alter column amount_min type numeric(5,2),
      alter column amount_max type numeric(5,2);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'restaurant_prices_range'
  ) then
    alter table public.restaurant_prices
      add constraint restaurant_prices_range check (amount_max >= amount_min);
  end if;
end $$;

create index if not exists idx_restaurant_prices_restaurant
  on public.restaurant_prices (restaurant_id);

drop trigger if exists trg_restaurant_prices_updated_at on public.restaurant_prices;
create trigger trg_restaurant_prices_updated_at
before update on public.restaurant_prices
for each row execute function public.set_updated_at();

-- 3) Recalcul des agrégats du restaurant --------------------------------------
-- security definer : l'auteur d'une déclaration (non-admin) ne peut pas écrire
-- dans restaurants (RLS admin-only). Le trigger s'exécute donc avec les droits
-- du propriétaire, comme public.recalc_restaurant_rating pour les avis.
create or replace function public.apply_restaurant_prices(rid bigint)
returns void
language sql
security definer
set search_path = public
as $$
  update public.restaurants r
  set price_count = agg.cnt,
      -- Arrondi vers l'extérieur (floor / ceil) : mieux vaut annoncer une
      -- fourchette un peu large que faire mentir l'affichage d'un euro.
      -- MAIS quand les deux médianes sont égales, il n'y a pas de fourchette à
      -- élargir : une seule déclaration à 11,90 doit donner « ~12 € » et non
      -- « 11-12 € ». Dans ce cas, arrondi à l'euro le plus proche des deux
      -- côtés — le front affiche alors « ~12 € » (low = high).
      price_low = case
        when agg.m_low is null then null
        when agg.m_low = agg.m_high then round(agg.m_low::numeric)::int
        else floor(agg.m_low)::int
      end,
      price_high = case
        when agg.m_high is null then null
        when agg.m_low = agg.m_high then round(agg.m_high::numeric)::int
        else ceil(agg.m_high)::int
      end
  from (
    select
      count(*)::int as cnt,
      -- Aucune déclaration → percentile_cont renvoie NULL → prix inconnu.
      percentile_cont(0.5) within group (order by amount_min::float8) as m_low,
      percentile_cont(0.5) within group (order by amount_max::float8) as m_high
    from public.restaurant_prices
    where restaurant_id = rid
  ) agg
  where r.id = rid;
$$;

create or replace function public.recalc_restaurant_prices()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  rid bigint := coalesce(new.restaurant_id, old.restaurant_id);
begin
  perform public.apply_restaurant_prices(rid);

  -- Si un update a déplacé la déclaration vers un autre resto, recalculer l'ancien.
  if tg_op = 'UPDATE' and new.restaurant_id is distinct from old.restaurant_id then
    perform public.apply_restaurant_prices(old.restaurant_id);
  end if;

  return null; -- trigger AFTER
end;
$$;

drop trigger if exists trg_restaurant_prices_recalc on public.restaurant_prices;
create trigger trg_restaurant_prices_recalc
after insert or update or delete on public.restaurant_prices
for each row execute function public.recalc_restaurant_prices();

-- 4) Rattrapage des agrégats ---------------------------------------------------
-- Les déclarations déjà en base n'ont pas déclenché le trigger (absent pendant
-- la migration), et celles qui existaient ont pu être agrégées par une logique
-- antérieure (quartiles, quorum de 3, arrondi différent). On recalcule tout le
-- catalogue : les restaurants sans déclaration retombent à 0 / NULL.
-- On rappelle la fonction plutôt que de répéter son calcul : la règle d'arrondi
-- ne doit vivre qu'à un seul endroit.
select public.apply_restaurant_prices(id) from public.restaurants;

-- 5) RLS -----------------------------------------------------------------------
alter table public.restaurant_prices enable row level security;

-- Lecture restreinte à sa propre déclaration : la fiche n'affiche que les
-- agrégats, personne n'a besoin de savoir ce que chacun dépense.
drop policy if exists "restaurant_prices select own" on public.restaurant_prices;
create policy "restaurant_prices select own"
on public.restaurant_prices for select to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  )
);

drop policy if exists "restaurant_prices insert own" on public.restaurant_prices;
create policy "restaurant_prices insert own"
on public.restaurant_prices for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "restaurant_prices update own" on public.restaurant_prices;
create policy "restaurant_prices update own"
on public.restaurant_prices for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "restaurant_prices delete own" on public.restaurant_prices;
create policy "restaurant_prices delete own"
on public.restaurant_prices for delete to authenticated
using (user_id = auth.uid());

-- Modération : un admin peut supprimer n'importe quelle déclaration.
drop policy if exists "restaurant_prices delete admin" on public.restaurant_prices;
create policy "restaurant_prices delete admin"
on public.restaurant_prices for delete to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  )
);
