-- =============================================================================
-- Votes sur les avis (style Reddit : upvote / downvote) — 2026-06-27
-- Un utilisateur a au plus UN vote par avis (valeur +1 ou -1), changeable ou
-- retirable. Le score d'un avis = somme des valeurs. Lecture par tous les
-- authentifiés ; on ne gère que son propre vote.
--
-- À exécuter sur le projet Supabase (ref ilonqaqyqmvsfskwgqka).
-- =============================================================================

-- 1) Table ---------------------------------------------------------------------
create table if not exists public.review_votes (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id    uuid   not null default auth.uid() references auth.users(id) on delete cascade,
  review_id  bigint not null references public.reviews(id) on delete cascade,
  value      smallint not null check (value in (-1, 1)),
  unique (user_id, review_id)
);

create index if not exists review_votes_review_idx
  on public.review_votes (review_id);

-- 2) RLS -----------------------------------------------------------------------
alter table public.review_votes enable row level security;

drop policy if exists "review_votes select authenticated" on public.review_votes;
create policy "review_votes select authenticated"
on public.review_votes for select to authenticated
using (true);

drop policy if exists "review_votes insert own" on public.review_votes;
create policy "review_votes insert own"
on public.review_votes for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "review_votes update own" on public.review_votes;
create policy "review_votes update own"
on public.review_votes for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "review_votes delete own" on public.review_votes;
create policy "review_votes delete own"
on public.review_votes for delete to authenticated
using (user_id = auth.uid());
