-- =============================================================================
-- Succès / achievements — déblocages par utilisateur — 2026-07-02
-- Le CATALOGUE des succès (intitulé, phrase, condition, icône) vit en dur côté
-- front (src/data/achievements.ts). Cette table ne stocke QUE les obtentions :
-- une ligne = un succès débloqué par un user. Générique → tout futur succès
-- s'y range sans migration.
--
-- À exécuter sur le projet Supabase (ref ilonqaqyqmvsfskwgqka).
-- =============================================================================

-- 1) Table ---------------------------------------------------------------------
create table if not exists public.user_achievements (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null default auth.uid() references auth.users(id) on delete cascade,
  achievement_id text not null,
  unlocked_at    timestamptz not null default now(),
  unique (user_id, achievement_id)
);

create index if not exists user_achievements_user_idx
  on public.user_achievements (user_id);

-- 2) RLS -----------------------------------------------------------------------
-- Chacun ne voit et ne débloque QUE ses propres succès. Pas d'update/delete :
-- un succès est définitif (reset éventuel = via SQL admin).
alter table public.user_achievements enable row level security;

drop policy if exists "user_achievements select own" on public.user_achievements;
create policy "user_achievements select own"
on public.user_achievements for select to authenticated
using (user_id = auth.uid());

drop policy if exists "user_achievements insert own" on public.user_achievements;
create policy "user_achievements insert own"
on public.user_achievements for insert to authenticated
with check (user_id = auth.uid());
