-- =============================================================================
-- Menus restaurants (multi-formats) — 2026-06-21
-- Un menu de resto peut être : un LIEN (page web), un PDF, ou une IMAGE (photo
-- de la carte). Modèle collaboratif calqué sur public.restaurant_photos :
-- contenu créé par les collaborateurs, modéré par les admins.
--
-- Les fichiers (pdf/image) vont dans le bucket EXISTANT `restaurant-photos`,
-- sous-dossier `{slug}/menu/…`. Les policies storage de ce bucket (insert/delete
-- own + delete admin, basées sur bucket_id) couvrent déjà ces fichiers → on ne
-- crée AUCUNE policy storage ici. La base ne porte que des métadonnées.
--
-- À exécuter sur le projet Supabase (ref ilonqaqyqmvsfskwgqka).
-- =============================================================================

-- 1) Table de métadonnées ------------------------------------------------------
create table if not exists public.restaurant_menus (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  user_id       uuid   not null default auth.uid() references auth.users(id) on delete cascade,
  kind          text   not null check (kind in ('link', 'pdf', 'image')),
  url           text,                 -- renseigné si kind='link'
  storage_path  text   unique,        -- renseigné si kind in ('pdf','image') ; chemin bucket
  title         text,                 -- libellé optionnel (ex. "Carte des vins")
  position      int    not null default 0,
  -- Cohérence : un lien porte une url ; un pdf/image porte un chemin de fichier.
  constraint restaurant_menus_payload check (
    (kind = 'link'  and url is not null) or
    (kind in ('pdf', 'image') and storage_path is not null)
  )
);

create index if not exists idx_restaurant_menus_restaurant
  on public.restaurant_menus (restaurant_id, position, created_at);

-- 2) RLS table -----------------------------------------------------------------
alter table public.restaurant_menus enable row level security;

drop policy if exists "restaurant_menus select authenticated" on public.restaurant_menus;
create policy "restaurant_menus select authenticated"
on public.restaurant_menus for select to authenticated
using (true);

-- Un utilisateur n'écrit que sa propre entrée ; un admin peut attribuer à un
-- autre user_id (poster au nom d'un autre).
drop policy if exists "restaurant_menus insert own" on public.restaurant_menus;
create policy "restaurant_menus insert own"
on public.restaurant_menus for insert to authenticated
with check (
  user_id = auth.uid()
  or exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  )
);

drop policy if exists "restaurant_menus delete own" on public.restaurant_menus;
create policy "restaurant_menus delete own"
on public.restaurant_menus for delete to authenticated
using (user_id = auth.uid());

-- Modération : un admin peut supprimer n'importe quelle entrée.
drop policy if exists "restaurant_menus delete admin" on public.restaurant_menus;
create policy "restaurant_menus delete admin"
on public.restaurant_menus for delete to authenticated
using (
  exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'admin'
  )
);
